/* Aartha Analytics static platform — accessible, dependency-free, and ready to connect to a CMS or analytics provider. */
const app = document.getElementById('app');

// Provider-agnostic event layer. Attach a production analytics provider to `window.aarthaAnalyticsProvider.track` when ready.
const analytics = {
  track(event, properties = {}) {
    const payload = { event, properties, timestamp: new Date().toISOString() };
    window.dispatchEvent(new CustomEvent('aartha:analytics', { detail: payload }));
    if (Array.isArray(window.dataLayer)) window.dataLayer.push(payload);
    if (window.aarthaAnalyticsProvider && typeof window.aarthaAnalyticsProvider.track === 'function') window.aarthaAnalyticsProvider.track(event, properties);
  }
};
let calculatorTracked = false;

const routes = {
  '/': { title: 'Aartha Analytics — Turning Insight Into Growth', description: 'Digital growth, analytics and strategy for better business decisions.' },
  '/about': { title: 'About Aartha Analytics', description: 'Why Aartha connects business thinking, research, digital execution and analytics.' },
  '/how-we-work': { title: 'How We Work | Aartha Analytics', description: 'A structured path from business problem to measurable growth.' },
  '/who-we-help': { title: 'Who We Help | Aartha Analytics', description: 'Growth support for startups, SMEs, established businesses and organizations.' },
  '/work': { title: 'Selected Work | Aartha Analytics', description: 'Selected projects and the business challenges behind them.' },
  '/insights': { title: 'Aartha Insights', description: 'Ideas, data and research for better business decisions.' },
  '/research': { title: 'Aartha Research', description: 'Forthcoming research on Nepal’s digital economy and business growth.' },
  '/growth-diagnostic': { title: 'Growth Diagnostic | Aartha Analytics', description: 'Find your potential growth opportunity with a guided directional assessment.' },
  '/contact': { title: 'Start a Conversation | Aartha Analytics', description: 'Talk to Aartha Analytics about the business challenge you are trying to solve.' },
  '/services': { title: 'Services | Aartha Analytics', description: 'Digital growth, analytics, strategy and business support built around your challenge.' }
};

const serviceData = {
  'digital-growth': { eyebrow: 'Digital Growth', title: 'Build the digital presence your next customers can find.', intro: 'Digital growth brings visibility, relevance and conversion together so your business can create a reliable route to new customers.', problem: 'You have a valuable offer, but your digital presence is not consistently creating attention or inquiries.', solution: 'We combine search, content, social channels and measurement into a practical growth system.', outcomes: ['Search visibility', 'Qualified traffic', 'More informed next steps'], services: ['SEO', 'Digital marketing', 'Content strategy', 'Social media', 'Digital presence'] },
  'digital-marketing': { eyebrow: 'Digital Marketing', title: 'Make every digital channel work harder for the business.', intro: 'A focused digital marketing plan connects the right message, channel and audience to a measurable business objective.', problem: 'Channels are active but marketing activity does not have a clear commercial direction.', solution: 'We shape campaigns around customer behavior, clear objectives and a shared measurement plan.', outcomes: ['Clearer channel priorities', 'Better campaign learning', 'More useful reporting'], services: ['Channel strategy', 'Campaign planning', 'Content direction', 'Lead generation', 'Marketing analytics'] },
  'seo': { eyebrow: 'SEO Nepal', title: 'Help the right customers discover you when they are already searching.', intro: 'Search engine optimization makes your business easier to find, understand and choose at the moments of highest intent.', problem: 'Your future customers search for solutions, but they are not consistently finding your business.', solution: 'We connect technical foundations, useful content and search intent to build durable organic visibility.', outcomes: ['Search visibility', 'Organic traffic', 'Qualified leads'], services: ['Technical SEO', 'Search content', 'Local SEO', 'Keyword research', 'Performance reporting'] },
  'social-media': { eyebrow: 'Social Media', title: 'Give your brand a clearer, more useful role in the conversation.', intro: 'Social media works best when content, customer understanding and business objectives are considered together.', problem: 'You are posting consistently but do not have enough clarity on what the activity is helping to achieve.', solution: 'We develop channel priorities, content systems and measurement that connect engagement to business value.', outcomes: ['Better brand recall', 'Stronger audience connection', 'Meaningful engagement'], services: ['Content planning', 'Channel strategy', 'Social campaigns', 'Community insights', 'Reporting'] },
  'marketing-advertising': { eyebrow: 'Marketing & Advertising', title: 'Turn marketing investment into useful evidence for growth.', intro: 'Performance marketing is more valuable when advertising decisions are connected to the customer journey, not just short-term clicks.', problem: 'You are investing in advertising without a clear view of cost, quality or the next opportunity.', solution: 'We plan, run and learn from campaigns using practical performance measurement.', outcomes: ['More informed spend', 'Lead quality insight', 'Campaign learning'], services: ['Campaign strategy', 'Performance marketing', 'Advertising', 'Creative direction', 'Lead generation'] },
  'data-analytics': { eyebrow: 'Data & Analytics', title: 'See the business clearly enough to make the next decision.', intro: 'Business and marketing analytics turn scattered data into a concise view of performance, questions and opportunities.', problem: 'You have data, reports and metrics, but not enough actionable insight.', solution: 'We identify useful KPIs, create clear dashboards and translate evidence into focused actions.', outcomes: ['Useful KPIs', 'Clearer decisions', 'Performance visibility'], services: ['Business analytics', 'Marketing analytics', 'Dashboards', 'KPI design', 'Performance measurement'] },
  'data-visualization': { eyebrow: 'Data Visualization', title: 'Make complex information easier to see, share and act on.', intro: 'A well-designed visual tells the story in the data without making people work to find the important point.', problem: 'Important information gets lost in spreadsheets, dense reports or inconsistent charts.', solution: 'We create visual systems and reporting views that bring signal, context and clarity to the surface.', outcomes: ['Clear communication', 'Faster understanding', 'Decision-ready reporting'], services: ['Dashboard design', 'Report design', 'Data storytelling', 'KPI visualization', 'Interactive charts'] },
  'business-development': { eyebrow: 'Business Development', title: 'Find and focus the opportunities that can move the business forward.', intro: 'Business development begins with customer, market and competitive understanding — then turns it into a practical path forward.', problem: 'You see possible opportunities but need a stronger basis for choosing where to focus.', solution: 'We bring research, market intelligence and growth planning into one decision-making process.', outcomes: ['Opportunity clarity', 'Stronger positioning', 'Focused growth plan'], services: ['Growth strategy', 'Market entry', 'Competitor analysis', 'Strategic planning', 'Opportunity mapping'] },
  'market-research': { eyebrow: 'Market Research', title: 'Replace assumptions with a clearer view of the market.', intro: 'Research gives business decisions context: who your customer is, what they need, and where your opportunity may be.', problem: 'A key decision needs more evidence about customers, competitors or the market.', solution: 'We define the right questions, organize evidence and present findings people can use.', outcomes: ['Customer understanding', 'Market context', 'Decision evidence'], services: ['Customer research', 'Market analysis', 'Competitor research', 'Survey design', 'Insight reporting'] },
  'business-support': { eyebrow: 'Business Support', title: 'Create practical structure behind sustainable growth.', intro: 'Business support gives operational information and processes the clarity needed to support better decisions.', problem: 'Growth is adding pressure to reporting, processes or foundational business administration.', solution: 'We help improve reporting, process visibility and support systems around the business.', outcomes: ['Clearer reporting', 'Stronger processes', 'Operational confidence'], services: ['Reporting', 'Process improvement', 'Payroll support', 'Taxation support', 'Business documentation'] }
};

const navLinks = [
  ['What We Do', '/services'], ['How We Work', '/how-we-work'], ['Who We Help', '/who-we-help'], ['Work', '/work'], ['Insights', '/insights'], ['About', '/about']
];

const icon = (name) => ({
  plus: '<span aria-hidden="true">+</span>', arrow: '<span class="arrow" aria-hidden="true">→</span>', check: '<span aria-hidden="true">✓</span>'
}[name] || '');

function link(label, href, className = '') { return `<a href="#${href}" class="${className}">${label}</a>`; }
function buttonLink(label, href, className = 'btn btn--orange') { return `<a href="#${href}" class="${className}">${label} ${icon('arrow')}</a>`; }

function header(path) {
  return `<header class="site-header">
    <div class="nav container">
      <a class="brand" href="#/" aria-label="Aartha Analytics home"><span class="brand-mark"><span>A</span></span><span>Aartha Analytics</span></a>
      <nav class="nav-links" aria-label="Primary navigation">
        ${navLinks.map(([label, href]) => `<a href="#${href}" ${path === href ? 'aria-current="page"' : ''}>${label}</a>`).join('')}
        <a href="#/contact">Start a Conversation</a>
      </nav>
      <div class="nav-actions"><a href="#/contact" class="btn btn--orange">Start a Conversation ${icon('arrow')}</a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button></div>
    </div>
  </header>`;
}

function footer() {
  return `<section class="final-cta"><div class="container final-cta-grid"><div><p class="eyebrow">Your next opportunity</p><h2>What's your next growth opportunity?</h2><p>Tell us the business challenge you are trying to solve. We will help you find a useful place to begin.</p></div>${buttonLink('Start a Conversation', '/contact', 'btn btn--white')}</div></section>
  <footer class="footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="#/"><span class="brand-mark"><span>A</span></span><span>Aartha Analytics</span></a><p class="footer-tagline">Turning Insight Into Growth.</p><p class="footer-signals">DIGITAL · DATA · STRATEGY · GROWTH</p></div><div><h3>Explore</h3>${link('What We Do','/services')}${link('How We Work','/how-we-work')}${link('Who We Help','/who-we-help')}${link('Work','/work')}</div><div><h3>Learn</h3>${link('Insights','/insights')}${link('Aartha Research','/research')}${link('About','/about')}${link('Growth Diagnostic','/growth-diagnostic')}</div><div><h3>Connect</h3>${link('Start a Conversation','/contact')}<a href="#/contact">LinkedIn</a><a href="#/contact">Facebook</a><a href="#/contact">Instagram</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Aartha Analytics. All rights reserved.</span><span class="footer-legal"><a href="#/contact">Privacy Policy</a><a href="#/contact">Terms</a><a href="#/contact">Cookie Policy</a></span></div></div></footer>`;
}

function hero() {
  return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Digital · Data · Strategy · Growth</p><h1>Turn Business Challenges Into <span class="accent">Growth Opportunities.</span></h1><p class="hero-lede">Aartha Analytics combines digital marketing, business strategy and data analytics to help businesses make better decisions, reach the right customers and grow with confidence.</p><div class="hero-actions">${buttonLink('Find Your Growth Opportunity', '/growth-diagnostic')} ${buttonLink('Explore Our Capabilities', '/services', 'btn btn--dark-ghost')}</div><div class="hero-proof"><span><i></i> Insight-led</span><span><i></i> Business-first</span><span><i></i> Evidence-informed</span></div></div>
  <div class="hero-panel" aria-label="Aartha data pathway illustration"><div class="signal-map"><svg viewBox="0 0 520 296" role="img" aria-label="A connected pathway from business challenge to growth"><path d="M54 55 C140 68, 110 152, 218 150 S270 62, 352 103 S406 220, 472 211" /><path class="active-path" d="M54 55 C140 68, 110 152, 218 150 S270 62, 352 103 S406 220, 472 211" /><circle class="node" cx="54" cy="55" r="8"/><circle class="node" cx="218" cy="150" r="8"/><circle class="node" cx="352" cy="103" r="8"/><circle class="node node--orange" cx="472" cy="211" r="10"/><circle class="node--orange" cx="133" cy="112" r="5"/><circle class="node" cx="412" cy="151" r="5"/></svg><span class="signal-label signal-label--one">BUSINESS CHALLENGE</span><span class="signal-label signal-label--two">INSIGHT · STRATEGY</span><span class="signal-label signal-label--three">MEASURABLE GROWTH</span></div><div class="pathway-picker"><h2>What are you trying to achieve?</h2><div class="pathway-options" role="group" aria-label="Growth goals">${['More Customers','Better Visibility','Better Marketing ROI','Better Business Decisions','Market Expansion','Better Data'].map((x,i) => `<button class="pathway-option ${i===0?'is-active':''}" data-pathway="${x}">${x}</button>`).join('')}</div><div class="pathway-result"><div><small>Recommended Aartha Pathway</small><strong id="pathway-result">Digital Growth + Analytics + Strategy</strong></div><a href="#/growth-diagnostic" class="text-link">Explore path ${icon('arrow')}</a></div></div></div></div></section>`;
}

const problems = [
  ['01','More Customers', 'Your business has value, but customer acquisition isn’t consistent.'], ['02','Better Visibility', 'Your audience isn’t finding or remembering your brand.'], ['03','Better Marketing ROI', 'You are spending money without knowing exactly what is working.'], ['04','Better Decisions', 'You have data but not enough actionable insight.'], ['05','Market Expansion', 'You see opportunities but need better market intelligence.'], ['06','Operational Growth', 'Your business is growing but your systems need structure.']
];
const capabilities = [
  ['01','Digital Growth',['SEO','Digital Marketing','Social Media','Content','Digital Presence'],'/services/digital-growth'], ['02','Marketing & Advertising',['Advertising','Campaign Strategy','Performance Marketing','Lead Generation','Creative Strategy'],'/services/marketing-advertising'], ['03','Data & Analytics',['Business Analytics','Marketing Analytics','Data Visualization','Dashboards','Performance Measurement'],'/services/data-analytics'], ['04','Business Development',['Market Research','Competitor Analysis','Growth Strategy','Market Entry','Strategic Planning'],'/services/business-development'], ['05','Business Support',['Payroll','Taxation','Reporting','Process Improvement'],'/services/business-support']
];

function homePage() {
  return `<main id="main-content">${hero()}
    <section class="section section--light"><div class="container"><div class="section-heading"><p class="eyebrow">The challenge</p><h2>Your Business Doesn't Need More Noise. It Needs Direction.</h2><p>Growth gets harder when the business problem is unclear. Start with the outcome you need, then build a smarter path to it.</p></div><div class="problem-grid">${problems.map(([num,title,copy]) => `<article class="problem-card"><div class="icon" aria-hidden="true">${num}</div><h3>${title}</h3><p>${copy}</p><a class="text-link" href="#/growth-diagnostic">Find direction ${icon('arrow')}</a></article>`).join('')}</div></div></section>
    <section class="section section--navy"><div class="container"><div class="section-heading"><p class="eyebrow">The difference</p><h2>Marketing Is Only Part of Growth.</h2></div><div class="comparison"><div class="compare-panel"><span class="small-title">Traditional Agency</span><div class="compare-list"><span>Content</span><span>Ads</span><span>SEO</span><span>Social</span></div></div><div class="compare-middle"></div><div class="compare-panel compare-panel--aartha"><span class="small-title">Aartha Analytics</span><div class="compare-list"><span>Research</span><span>Strategy</span><span>Digital</span><span>Data</span><span>Business</span></div></div><div class="comparison-copy"><p>Businesses don't always have a marketing problem. Sometimes the real problem is positioning, customer understanding, decision-making, measurement or market opportunity.</p><p>We bring research, strategy, digital execution and analytics together to solve the underlying problem.</p></div></div></div></section>
    <section class="section section--navy"><div class="container"><div class="section-heading"><p class="eyebrow">A structured methodology</p><h2>The Aartha Growth Framework™</h2><p>Every engagement begins with a useful question, follows the evidence and turns learning into a next action.</p></div>${framework()}</div></section>
    <section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Capabilities</p><h2>Everything You Need To Build Better Growth.</h2><p>Choose the capability that fits the challenge today. We can connect the pieces as your needs evolve.</p></div><div class="capability-grid">${capabilities.map(([n,title,items,href]) => `<article class="capability-card"><span class="cap-no">${n}</span><h3>${title}</h3><ul>${items.map(i=>`<li>${i}</li>`).join('')}</ul><a href="#${href}" class="text-link">Explore ${title} ${icon('arrow')}</a></article>`).join('')}</div></div></section>
    <section class="section section--navy"><div class="container"><div class="section-heading"><p class="eyebrow">Who we help</p><h2>Built Around Your Business Stage.</h2><p>Different stages need different evidence, systems and growth support.</p></div><div class="audience-grid">${audienceCards()}</div></div></section>
    <section class="section section--light"><div class="container">${diagnosticMarkup()}</div></section>
    <section class="section section--navy"><div class="container"><div class="section-heading"><p class="eyebrow">Analytics demo</p><h2>See Your Business Through Data.</h2><p>This interactive demonstration shows how a clearer view of performance can make the next decision easier. All values are illustrative demo data.</p></div>${dashboard()}</div></section>
    <section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Selected projects</p><h2>Work That Creates Impact.</h2><p>We do not publish client results or names without permission. These selected project types show the problems we are designed to help solve.</p></div><div class="work-grid">${projectCards()}</div></div></section>
    <section class="section section--navy"><div class="container"><div class="section-heading"><p class="eyebrow">Aartha insights</p><h2>Ideas, Data and Research for Better Business Decisions.</h2><p>Clear thinking around digital growth, analytics and the Nepal market.</p></div>${articles()}</div></section>
    <section class="section"><div class="container"><div class="team-strip"><div class="team-note"><p class="eyebrow">The people behind Aartha</p><h2>Expertise should be clear — and earned.</h2><p>Team member information will be published when it is available. We will never invent credentials, biographies or client relationships.</p>${buttonLink('About Aartha', '/about', 'btn btn--ghost')}</div><div class="team-members">${teamCards()}</div></div></div></section>
  </main>`;
}

function framework() {
  const stages = [['01','Understand','Research the business, market, customer and competition.'],['02','Strategize','Identify opportunities and define the growth plan.'],['03','Execute','Implement the appropriate solutions.'],['04','Measure','Track meaningful KPIs.'],['05','Optimize','Improve based on evidence.'],['06','Grow','Create sustainable business growth.']];
  return `<div class="framework" role="list">${stages.map(([num,title,copy],i)=>`<button class="framework-stage ${i===0?'is-active':''}" type="button" data-stage="${i}" role="listitem"><span class="stage-number">${num}</span><h3>${title}</h3><p>${copy}</p></button>`).join('')}</div>`;
}

function audienceCards() { const data = [['01','Startups','Build visibility and acquire early customers.'],['02','SMEs','Create sustainable digital growth.'],['03','Established Businesses','Optimize marketing and decision-making.'],['04','Organizations','Use research, analytics and strategy.'],['05','Global Clients','Access digital, research and analytics capability remotely.']]; return data.map(([n,t,p])=>`<article class="audience-card"><span class="audience-no">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join(''); }

function diagnosticMarkup() {
  return `<div class="diagnostic-wrap"><aside class="diagnostic-intro"><p class="eyebrow">Interactive growth diagnostic</p><h2>Find Your Growth Opportunity.</h2><p>Answer a few questions to discover where your biggest growth opportunity may be.</p><div class="diagnostic-points"><span><b>1</b>A practical directional assessment</span><span><b>2</b>A recommendation, not a sales pitch</span><span><b>3</b>A clear next step if it feels useful</span></div></aside><div class="diagnostic" id="diagnostic" aria-live="polite"></div></div>`;
}

function dashboard() {
  return `<div class="dashboard"><div class="dashboard-top"><strong>Growth overview</strong><span class="demo-badge">DEMO DATA</span></div><div class="dashboard-tabs" role="tablist">${['Marketing','Sales','Customers','Finance'].map((x,i)=>`<button class="dash-tab ${i===0?'active':''}" role="tab" aria-selected="${i===0}" data-dash="${x}">${x}</button>`).join('')}</div><div class="dash-main"><div class="kpi-grid" id="kpi-grid"></div><div class="dash-charts"><article class="chart-card"><h3 id="chart-title">Monthly revenue trend</h3><svg class="line-chart" viewBox="0 0 440 164" preserveAspectRatio="none" role="img" aria-label="Illustrative monthly performance trend"><defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f97316" stop-opacity=".25"/><stop offset="1" stop-color="#f97316" stop-opacity="0"/></linearGradient></defs><path class="gridline" d="M0 20H440M0 63H440M0 106H440M0 149H440"/><path class="area" id="area-path" d="M0,138 L55,121 L110,128 L165,88 L220,101 L275,57 L330,75 L385,29 L440,42 L440,164 L0,164Z"/><path class="line" id="line-path" d="M0,138 L55,121 L110,128 L165,88 L220,101 L275,57 L330,75 L385,29 L440,42"/></svg></article><article class="chart-card"><h3>Channel contribution</h3><div class="channel-list" id="channel-list"></div><div class="dash-donut-row"><div class="donut" role="img" aria-label="Illustrative mix: 42 percent paid, 34 percent organic, 24 percent other"></div><p class="donut-label"><b>Acquisition mix</b>Paid, organic and other sources at a glance.</p></div></article></div></div><p class="dashboard-note">Illustrative demo data only. This dashboard is not client reporting.</p></div>`;
}

function projectCards() { const projects = [['Digital growth system','Digital Growth','Low digital visibility','SEO + Content + Analytics','Approach shown; results are confidential.',''],['Market opportunity mapping','Research','Unclear market opportunity','Customer + competitor research','Selected project type; no client information published.','project-visual--market'],['Operational reporting view','Business Support','Scattered reporting','KPI design + reporting structure','Selected project type; no client information published.','project-visual--ops']]; return projects.map(([title,industry,challenge,solution,result,style])=>`<article class="project-card"><div class="project-visual ${style}"><span>SELECTED PROJECT TYPE</span></div><div class="project-copy"><small>${industry}</small><h3>${title}</h3><dl><div><dt>Challenge</dt><dd>${challenge}</dd></div><div><dt>Solution</dt><dd>${solution}</dd></div><div><dt>Result</dt><dd>${result}</dd></div></dl><p class="note">Names and performance figures are omitted to protect client confidentiality.</p></div></article>`).join(''); }

function articles() { const data=[['Growth','Why every marketing plan needs a measurement question','The best reporting doesn’t begin after the campaign; it begins while the plan is being made.','6 min read'],['Nepal Market','A practical view of Nepal’s digital growth opportunity','What businesses should look for before turning digital activity into a growth priority.','5 min read'],['Analytics','From metrics to decisions: what a useful dashboard does','A dashboard earns attention when it makes the next decision easier.','4 min read']]; return `<div class="insight-grid">${data.map(([cat,title,copy,time],i)=>`<article class="article"><span class="article-category">${cat}</span><h3>${title}</h3><p>${copy}</p><div class="article-meta"><span>Aartha Analytics</span><span>•</span><span>${time}</span></div><a href="#/insights" class="text-link">Read insight ${icon('arrow')}</a></article>`).join('')}</div>`; }

function teamCards() { return [['[AA]','[TEAM MEMBER NAME]','Profile and expertise will be added with verified information.'],['[AA]','[TEAM MEMBER NAME]','Profile and expertise will be added with verified information.'],['[AA]','[TEAM MEMBER NAME]','Profile and expertise will be added with verified information.']].map(([initials,name,bio])=>`<article class="team-card"><div class="avatar">${initials}</div><div><span class="placeholder-label">TEAM PROFILE</span><h3>${name}</h3><p>${bio}</p></div></article>`).join(''); }

function pageHero(eyebrow, title, intro) { return `<section class="page-hero"><div class="container"><p class="bread"><a href="#/">Home</a> / ${eyebrow}</p><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${intro}</p></div></section>`; }
function informationCards(items) { return `<div class="page-grid">${items.map(([n,t,p])=>`<article class="information-card"><span class="number">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div>`; }

function howWeWork() { const steps=[['01','Discover','Understand your business context, goals and current situation.'],['02','Diagnose','Clarify the underlying problem, opportunity and evidence needed.'],['03','Strategize','Define the right priorities, pathway and success measures.'],['04','Execute','Implement focused digital, data, research or business solutions.'],['05','Measure','Track the meaningful indicators behind the work.'],['06','Optimize','Learn from evidence and improve the approach.'],['07','Grow','Build a stronger foundation for sustainable next-stage growth.']]; return `<main id="main-content">${pageHero('How we work','From Business Problem To Business Growth.','Aartha uses a practical, evidence-informed process that adapts to the challenge — and makes room for learning along the way.')}<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">The process</p><h2>Clarity before activity.</h2><p>We do not begin by deciding on a channel. We begin by understanding the business question that needs to be answered.</p></div>${informationCards(steps)}</div></section><section class="section section--light"><div class="container"><div class="service-header"><div><p class="eyebrow">A flexible method</p><h2>Structured enough to be reliable. Flexible enough to be useful.</h2></div><div class="service-stat"><strong>Problem → insight → action</strong><span>One clear thread from a business challenge through to measurable progress.</span></div></div></div></section></main>`; }

function whoWeHelp() { const people=[['01','Startups','Build visibility, understand early customers and create a clearer route to acquisition.'],['02','SMEs','Create a more sustainable system for marketing, insight and business growth.'],['03','Established Businesses','Improve decision-making, marketing performance and digital transformation priorities.'],['04','Organizations','Use research, analytics and reporting to support strategy and communication.'],['05','Global Clients','Access digital, research and analytics capability remotely.']]; return `<main id="main-content">${pageHero('Who we help','Built for businesses at every stage of growth.','Aartha brings together the capabilities a business needs now, with a view toward the systems it will need next.')}<section class="section"><div class="container">${informationCards(people)}</div></section><section class="section section--light"><div class="container"><div class="section-heading"><p class="eyebrow">Not sure where to begin?</p><h2>Start with the business challenge, not the service list.</h2><p>Our growth diagnostic helps create a focused starting point in a few minutes.</p></div>${buttonLink('Find Your Growth Opportunity','/growth-diagnostic')}</div></section></main>`; }

function workPage() { return `<main id="main-content">${pageHero('Selected work','Projects built around business questions.','We protect client confidentiality and do not publish names, results or testimonials without approval. These project types explain where our capabilities can create value.')}<section class="section"><div class="container">${projectCards()}</div></section><section class="section section--light"><div class="container"><div class="section-heading"><p class="eyebrow">Work with us</p><h2>Have a similar challenge?</h2><p>Tell us the business problem. We will help you decide whether Aartha is the right growth partner to explore it with.</p></div>${buttonLink('Discuss a Similar Challenge','/contact')}</div></section></main>`; }

function insightsPage() { return `<main id="main-content">${pageHero('Aartha insights','Ideas, data and research for better business decisions.','A growing knowledge platform around strategy, digital growth, analytics, research and the Nepal market.')}<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Knowledge platform</p><h2>New perspectives are coming soon.</h2><p>We publish only original, useful content that we can responsibly stand behind. The first Aartha Insights articles are in development.</p></div><div class="page-grid">${informationCards([['01','Strategy','How to frame a business problem before choosing the activity.'],['02','Digital','Practical thinking for customer acquisition and digital presence.'],['03','Analytics','Making performance data easier to understand and act on.'],['04','Business','Growth systems and clearer operating decisions.'],['05','Nepal Market','Evidence-led observations about the local business landscape.'],['06','Research','Questions worth asking before a high-stakes decision.']])}</div></div></section></main>`; }

function researchPage() { const reports=[['01','Nepal SME Digital Adoption Report','Coming Soon'],['02','Nepal Digital Marketing Benchmark','Coming Soon'],['03','Nepal Consumer Digital Behavior Report','Coming Soon'],['04','Nepal Business Growth Index','Coming Soon']]; return `<main id="main-content">${pageHero('Aartha research','Research designed to make the market easier to understand.','Aartha Research will publish clear, responsible reports on the questions shaping the Nepal digital economy and business growth.')}<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Future reports</p><h2>Research in development.</h2><p>These reports are planned future publications. They are clearly marked until data collection, analysis and editorial review are complete.</p></div>${informationCards(reports.map(([n,t,p])=>[n,t,p]))}</div></section></main>`; }

function aboutPage() { const values=[['01','Our Purpose','Connect business thinking, research, digital execution and analytics so better information can become better action.'],['02','Our Mission','Help organizations find their most useful growth opportunities and pursue them with clarity.'],['03','Our Vision','A more evidence-informed business landscape, where insight supports sustainable growth.'],['04','Our Values','Clarity over noise. Useful evidence over assumptions. Honest partnership over inflated claims.']]; return `<main id="main-content">${pageHero('About Aartha','Why We Built Aartha.','Businesses have more information and digital channels than ever before. But more information does not automatically create better decisions.')}<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Our story</p><h2>Aartha was created to connect the pieces.</h2><p>Aartha Analytics brings business thinking, research, digital execution and analytics together. The goal is not simply more activity; it is more useful progress.</p></div>${informationCards(values)}</div></section><section class="section section--light"><div class="container"><div class="team-strip"><div class="team-note"><p class="eyebrow">Our team</p><h2>People, not invented profiles.</h2><p>Verified team biographies and LinkedIn profiles will appear here when they are ready to share.</p></div><div class="team-members">${teamCards()}</div></div></div></section></main>`; }

function servicesPage() { return `<main id="main-content">${pageHero('What we do','Growth capability, shaped around the real problem.','Aartha offers digital, data, strategy and business support as connected capabilities — not isolated activity lists.')}<section class="section"><div class="container"><div class="capability-grid">${capabilities.map(([n,title,items,href]) => `<article class="capability-card"><span class="cap-no">${n}</span><h3>${title}</h3><ul>${items.map(i=>`<li>${i}</li>`).join('')}</ul><a href="#${href}" class="text-link">Explore ${title} ${icon('arrow')}</a></article>`).join('')}</div></div></section><section class="section section--light"><div class="container"><div class="section-heading"><p class="eyebrow">Service design</p><h2>Problem → Solution → Outcome</h2><p>Every service is framed by the challenge it solves and the change it is designed to create.</p></div>${buttonLink('Find Your Growth Opportunity','/growth-diagnostic')}</div></section></main>`; }

function servicePage(data) { return `<main id="main-content">${pageHero(data.eyebrow,data.title,data.intro)}<section class="section"><div class="container"><div class="service-header"><div><p class="eyebrow">The business case</p><h2>Useful work begins with the underlying challenge.</h2></div><div class="service-stat"><strong>${data.outcomes.join(' · ')}</strong><span>The intended outcomes guide what is measured and improved.</span></div></div><div class="page-grid" style="margin-top:48px"><article class="information-card"><span class="number">01 · PROBLEM</span><h3>What may be getting in the way</h3><p>${data.problem}</p></article><article class="information-card"><span class="number">02 · SOLUTION</span><h3>How Aartha can help</h3><p>${data.solution}</p></article><article class="information-card"><span class="number">03 · OUTCOME</span><h3>What better could look like</h3><p>${data.outcomes.join(', ')}.</p></article></div></div></section><section class="section section--light"><div class="container"><div class="section-heading"><p class="eyebrow">Included capability</p><h2>A focused set of practical building blocks.</h2></div>${informationCards(data.services.map((x,i)=>[String(i+1).padStart(2,'0'),x,'Configured around your business context, objective and available evidence.']))}</div></section><section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Questions</p><h2>Frequently asked questions.</h2></div><div class="faq"><details><summary>How do we know if this is the right place to start?</summary><p>Begin with the growth diagnostic or a conversation about the business challenge. We will identify whether this capability is a useful fit before recommending work.</p></details><details><summary>Will the work include measurement?</summary><p>Yes. The most meaningful KPIs are agreed early so progress can be reviewed with context, not just activity metrics.</p></details><details><summary>Can this connect to other Aartha capabilities?</summary><p>Yes. Aartha’s approach is designed to connect digital, research, strategy and analytics when that produces a more useful outcome.</p></details></div></div></section></main>`; }

function diagnosticPage() { return `<main id="main-content">${pageHero('Growth diagnostic','Find Your Growth Opportunity.','A short directional assessment to help you identify a practical first pathway. It is not a formal business diagnosis.')}<section class="section section--light"><div class="container">${diagnosticMarkup()}</div></section></main>`; }

function calculator() { return `<section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Illustrative planning tool</p><h2>What Could Your Marketing Investment Look Like?</h2><p>Adjust the inputs to explore a simple scenario. Estimates are illustrative and do not guarantee future performance.</p></div><div class="calculator"><div class="calc-fields" id="calculator-fields"><div class="field"><label for="budget">Monthly advertising budget <span>NPR</span></label><input id="budget" type="number" min="0" value="50000"></div><div class="field"><label for="value">Average customer value <span>NPR</span></label><input id="value" type="number" min="1" value="12000"></div><div class="field"><label for="cpl">Estimated cost per lead <span>NPR</span></label><input id="cpl" type="number" min="1" value="800"></div><div class="field"><label for="rate">Estimated conversion rate <span>%</span></label><input id="rate" type="number" min="0" max="100" value="12"></div></div><div class="calc-results"><h3>Scenario estimate</h3><div class="result-metrics"><div class="result-metric"><span>Estimated leads</span><strong id="est-leads">63</strong></div><div class="result-metric"><span>Estimated customers</span><strong id="est-customers">8</strong></div><div class="result-metric"><span>Estimated revenue</span><strong id="est-revenue">NPR 96K</strong></div><div class="result-metric"><span>Estimated ROAS</span><strong id="est-roas">1.92×</strong></div></div><div class="mini-bars" aria-hidden="true"><i style="height:32%"></i><i style="height:48%"></i><i style="height:43%"></i><i style="height:68%"></i><i style="height:78%"></i><i style="height:92%"></i></div><p class="disclaimer">Break-even point: <strong id="break-even">5 customers</strong>. Illustrative scenario only; actual outcomes depend on many factors.</p></div></div></div></section>`; }

function contactPage() { return `<main id="main-content">${pageHero('Start a conversation',"Let's Talk About Growth.","Not sure what service you need? That's okay. Tell us the problem you're trying to solve.")}<section class="section section--light"><div class="container contact-grid"><aside class="contact-note"><p class="eyebrow">Start with the question</p><h1>A useful conversation is the first step.</h1><p>We will listen to the problem, ask a few practical questions and help you decide on the next useful action.</p><p class="disclaimer">Please do not include confidential business information in this initial form.</p></aside><form class="contact-form" id="contact-form" novalidate><div class="form-success" role="status">Thanks — your message is ready to be sent. Connect this form to your approved email or CRM service before publishing.</div><div class="form-grid"><div class="field"><label for="name">Name</label><input id="name" name="name" required><div class="form-error"></div></div><div class="field"><label for="organization">Organization</label><input id="organization" name="organization" required><div class="form-error"></div></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required><div class="form-error"></div></div><div class="field"><label for="phone">Phone <span>Optional</span></label><input id="phone" name="phone" type="tel"><div class="form-error"></div></div><div class="field"><label for="business">Business type</label><select id="business" name="business" required><option value="">Select one</option><option>Startup</option><option>Small Business</option><option>Medium Business</option><option>Established Business</option><option>Organization</option></select><div class="form-error"></div></div><div class="field"><label for="challenge">Biggest challenge</label><select id="challenge" name="challenge" required><option value="">Select one</option><option>Customer Acquisition</option><option>Brand Awareness</option><option>Analytics</option><option>Market Expansion</option><option>Operations</option><option>Other</option></select><div class="form-error"></div></div><div class="field field--full"><label for="goal">What would you like to achieve?</label><input id="goal" name="goal" required maxlength="160"><div class="form-error"></div></div><div class="field field--full"><label for="message">Tell us a little more <span>Optional</span></label><textarea id="message" name="message" maxlength="1000"></textarea><div class="form-error"></div></div></div><button class="btn btn--orange" type="submit">Start a Conversation ${icon('arrow')}</button></form></div></section></main>`; }

function render(path) {
  const cleaned = path.replace(/\/$/, '') || '/';
  const route = routes[cleaned] || (cleaned.startsWith('/services/') ? { title: `${serviceData[cleaned.split('/').pop()]?.eyebrow || 'Service'} | Aartha Analytics`, description: 'Aartha capability overview.' } : routes['/']);
  document.title = route.title;
  const meta = document.querySelector('meta[name="description"]'); if (meta) meta.content = route.description;
  let page;
  if (cleaned === '/') page = homePage();
  else if (cleaned === '/how-we-work') page = howWeWork();
  else if (cleaned === '/who-we-help') page = whoWeHelp();
  else if (cleaned === '/work') page = workPage();
  else if (cleaned === '/insights') page = insightsPage();
  else if (cleaned === '/research') page = researchPage();
  else if (cleaned === '/about') page = aboutPage();
  else if (cleaned === '/services') page = servicesPage();
  else if (cleaned === '/growth-diagnostic') page = diagnosticPage();
  else if (cleaned === '/contact') page = contactPage();
  else if (cleaned.startsWith('/services/') && serviceData[cleaned.split('/').pop()]) page = servicePage(serviceData[cleaned.split('/').pop()]);
  else page = homePage();
  const canonical = document.querySelector('link[rel="canonical"]'); if (canonical) canonical.href = `https://aarthaanalytics.com${cleaned}`;
  app.innerHTML = header(cleaned) + page + (cleaned === '/' ? calculator() : '') + footer();
  if (cleaned.startsWith('/services/')) analytics.track('service_viewed', { service: cleaned.split('/').pop() });
  if (cleaned === '/research') analytics.track('research_viewed');
  bindInteractions();
  window.scrollTo({ top: 0, behavior: 'auto' });
}

const diagnosticState = { step: 0, answers: {} };
const questions = [
  { key:'business', label:'Step 1 of 5', question:'What best describes your business?', choices:['Startup','Small Business','Medium Business','Established Business','Organization'] },
  { key:'challenge', label:'Step 2 of 5', question:'What is your biggest challenge right now?', choices:['Customer Acquisition','Brand Awareness','SEO','Social Media','Advertising','Analytics','Market Expansion','Competition','Operations','Other'] },
  { key:'goal', label:'Step 3 of 5', question:'What is the primary goal?', choices:['More Leads','More Sales','Better Visibility','Better Decisions','Market Expansion','Cost Efficiency','Brand Growth'] },
  { key:'assets', label:'Step 4 of 5', question:'Which digital assets do you already use?', multi:true, choices:['Website','Facebook','Instagram','TikTok','SEO','Google Business','Advertising','Analytics'] },
  { key:'measurement', label:'Step 5 of 5', question:'How would you describe your measurement maturity?', choices:["We don't measure much",'Basic metrics','Some analytics','Advanced dashboards'] }
];
function drawDiagnostic() {
  const el = document.getElementById('diagnostic'); if (!el) return;
  if (diagnosticState.step === 5) { el.innerHTML = diagnosticResult(); return; }
  const q = questions[diagnosticState.step]; const value = diagnosticState.answers[q.key] || (q.multi ? [] : '');
  el.innerHTML = `<div class="progress-row"><div class="progress-track" aria-label="Progress">${questions.map((_,i)=>`<i class="progress-dot ${i <= diagnosticState.step?'active':''}"></i>`).join('')}</div><span>${q.label}</span></div><span class="question-label">GROWTH CONTEXT</span><h3>${q.question}</h3><div class="choice-grid" role="group" aria-label="${q.question}">${q.choices.map(x=>`<button type="button" class="choice ${(q.multi ? value.includes(x) : value === x) ? 'selected' : ''}" data-choice="${x}">${q.multi && value.includes(x) ? '✓ ' : ''}${x}</button>`).join('')}</div><div class="diagnostic-actions">${diagnosticState.step ? '<button type="button" class="btn btn--ghost" id="diagnostic-back">Back</button>' : '<span></span>'}<button type="button" class="btn btn--orange" id="diagnostic-next" ${(!q.multi && !value) || (q.multi && !value.length) ? 'disabled' : ''}>${diagnosticState.step === 4 ? 'See my opportunity' : 'Continue'} ${icon('arrow')}</button></div>`;
  el.querySelectorAll('[data-choice]').forEach(btn => btn.addEventListener('click', () => { const choice=btn.dataset.choice; if (diagnosticState.step === 0 && !diagnosticState.answers.business) analytics.track('growth_diagnostic_started'); if(q.multi){ const old=diagnosticState.answers[q.key]||[]; diagnosticState.answers[q.key]=old.includes(choice)?old.filter(x=>x!==choice):[...old,choice]; } else diagnosticState.answers[q.key]=choice; drawDiagnostic(); }));
  const back=el.querySelector('#diagnostic-back'); if(back) back.addEventListener('click',()=>{ diagnosticState.step--; drawDiagnostic(); });
  el.querySelector('#diagnostic-next').addEventListener('click',()=>{ if (diagnosticState.step === 4) analytics.track('growth_diagnostic_completed'); diagnosticState.step++; drawDiagnostic(); });
}
function diagnosticResult() {
  const scores = { 'Digital Growth':0, 'Marketing & Advertising':0, 'Data & Analytics':0, 'Business Development':0, 'Business Support':0 };
  const a=diagnosticState.answers; const add=(key,n)=>scores[key]+=n;
  const challenge={ 'Customer Acquisition':['Digital Growth','Marketing & Advertising','Data & Analytics'], 'Brand Awareness':['Digital Growth','Marketing & Advertising'], 'SEO':['Digital Growth','Data & Analytics'], 'Social Media':['Digital Growth','Marketing & Advertising'], 'Advertising':['Marketing & Advertising','Data & Analytics'], 'Analytics':['Data & Analytics','Business Development'], 'Market Expansion':['Business Development','Digital Growth'], 'Competition':['Business Development','Data & Analytics'], 'Operations':['Business Support','Data & Analytics'], 'Other':['Business Development','Digital Growth'] };
  (challenge[a.challenge]||[]).forEach((x,i)=>add(x,3-i));
  ({'More Leads':['Digital Growth','Marketing & Advertising'], 'More Sales':['Marketing & Advertising','Data & Analytics'], 'Better Visibility':['Digital Growth'], 'Better Decisions':['Data & Analytics','Business Development'], 'Market Expansion':['Business Development'], 'Cost Efficiency':['Data & Analytics','Business Support'], 'Brand Growth':['Digital Growth','Marketing & Advertising']}[a.goal]||[]).forEach((x,i)=>add(x,2-i));
  if ((a.assets||[]).includes('Analytics')) add('Data & Analytics',2); if ((a.assets||[]).includes('SEO')) add('Digital Growth',1); if (a.measurement === "We don't measure much" || a.measurement === 'Basic metrics') add('Data & Analytics',2);
  const sorted=Object.entries(scores).sort((x,y)=>y[1]-x[1]); const primary=sorted[0][0], secondary=sorted[1][0]; const copy={ 'Digital Growth':'Your responses suggest that improving digital visibility and customer acquisition may be your strongest starting point.', 'Marketing & Advertising':'Your responses suggest a focused campaign and performance pathway may be the most useful next step.', 'Data & Analytics':'Your responses suggest that clearer measurement and decision-ready data may unlock the next opportunity.', 'Business Development':'Your responses suggest that market, customer or growth strategy clarity may be the most useful starting point.', 'Business Support':'Your responses suggest that stronger reporting and operational structure may support better growth.' }[primary];
  return `<div class="diagnostic-result"><span class="result-chip">YOUR GROWTH OPPORTUNITY</span><h3>Primary opportunity: ${primary}</h3><p>${copy}</p><p><strong>Secondary opportunity:</strong> ${secondary}</p><div class="path-result">${recommendations(primary).map(x=>`<span>${x}</span>`).join('')}</div>${buttonLink('Discuss Your Growth Opportunity','/contact')}<p class="disclaimer">This is an initial directional assessment, not a formal business diagnosis.</p><button type="button" class="text-link" id="restart-diagnostic">Start again ${icon('arrow')}</button></div>`;
}
function recommendations(primary) { return ({'Digital Growth':['Digital Marketing','SEO','Marketing Analytics'], 'Marketing & Advertising':['Campaign Strategy','Performance Marketing','Marketing Analytics'], 'Data & Analytics':['Business Analytics','Data Visualization','Performance Measurement'], 'Business Development':['Market Research','Competitor Analysis','Growth Strategy'], 'Business Support':['Reporting','Process Improvement','Business Analytics']})[primary]; }

function updateDashboard(tab = 'Marketing') {
  const sets={Marketing:{k:[['Marketing spend','NPR 48K','+12.4%'],['Leads','186','+18.7%'],['Conversion','6.8%','+0.9 pp'],['ROI','2.4×','+0.3×']],channels:[['Search',78],['Social',62],['Referral',46],['Direct',32]],path:'M0,138 L55,121 L110,128 L165,88 L220,101 L275,57 L330,75 L385,29 L440,42',title:'Monthly revenue trend'},Sales:{k:[['Sales pipeline','NPR 428K','+9.8%'],['Opportunities','56','+14.2%'],['Win rate','22.1%','+1.6 pp'],['Sales cycle','18d','−3 days']],channels:[['Qualified',76],['Proposal',55],['Negotiation',39],['Closed',28]],path:'M0,141 L55,132 L110,110 L165,113 L220,75 L275,80 L330,55 L385,65 L440,28',title:'Sales pipeline trend'},Customers:{k:[['New customers','29','+21.0%'],['Retention','84%','+3.1 pp'],['CAC','NPR 2.1K','−8.4%'],['Value','NPR 14K','+5.3%']],channels:[['Returning',81],['New',69],['Referral',51],['Partner',34]],path:'M0,143 L55,118 L110,125 L165,95 L220,103 L275,86 L330,59 L385,47 L440,33',title:'Customer growth trend'},Finance:{k:[['Revenue','NPR 1.24M','+16.8%'],['Gross margin','38%','+2.6 pp'],['Spend','NPR 498K','+4.0%'],['ROAS','2.5×','+0.3×']],channels:[['Core',85],['Growth',65],['Other',42],['New',26]],path:'M0,140 L55,136 L110,117 L165,101 L220,108 L275,68 L330,73 L385,40 L440,31',title:'Revenue trend'}};
  const data=sets[tab]; const k=document.getElementById('kpi-grid'), c=document.getElementById('channel-list'); if(!k || !data) return; k.innerHTML=data.k.map(([x,y,z])=>`<div class="kpi"><small>${x}</small><strong>${y}</strong><span>${z}</span></div>`).join(''); c.innerHTML=data.channels.map(([x,y])=>`<div class="channel"><span>${x}</span><div class="bar"><i style="width:${y}%"></i></div><b>${y}%</b></div>`).join(''); document.getElementById('line-path').setAttribute('d',data.path); document.getElementById('area-path').setAttribute('d',data.path+' L440,164 L0,164Z'); document.getElementById('chart-title').textContent=data.title;
}

function setupCalculator() { const fields=document.getElementById('calculator-fields'); if(!fields) return; const currency=new Intl.NumberFormat('en-US',{maximumFractionDigits:0}); const update=()=>{ const budget=Math.max(0,+document.getElementById('budget').value||0), value=Math.max(1,+document.getElementById('value').value||1), cpl=Math.max(1,+document.getElementById('cpl').value||1), rate=Math.min(100,Math.max(0,+document.getElementById('rate').value||0))/100; const leads=budget/cpl, customers=leads*rate, revenue=customers*value, roas=budget?revenue/budget:0, breakEven=Math.ceil(budget/value); document.getElementById('est-leads').textContent=currency.format(Math.round(leads)); document.getElementById('est-customers').textContent=currency.format(Math.round(customers)); document.getElementById('est-revenue').textContent=`NPR ${currency.format(Math.round(revenue/1000))}K`; document.getElementById('est-roas').textContent=`${roas.toFixed(2)}×`; document.getElementById('break-even').textContent=`${currency.format(breakEven)} customer${breakEven===1?'':'s'}`; }; fields.addEventListener('input',()=>{ if(!calculatorTracked){ analytics.track('calculator_used'); calculatorTracked=true; } update(); }); update(); }

function setupContactForm() { const form=document.getElementById('contact-form'); if(!form) return; let started=false; form.addEventListener('focusin',()=>{if(!started){analytics.track('consultation_started');started=true;}},{once:true}); form.addEventListener('submit', e=>{e.preventDefault(); let valid=true; form.querySelectorAll('[required]').forEach(field=>{const err=field.parentElement.querySelector('.form-error'); let message=''; if(!field.value.trim()) message='This field is required.'; else if(field.type==='email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value)) message='Enter a valid email address.'; err.textContent=message; field.setAttribute('aria-invalid',message?'true':'false'); if(message) valid=false;}); if(valid) { analytics.track('consultation_submitted'); form.querySelector('.form-success').classList.add('show'); form.querySelector('.form-success').focus?.(); } }); }

function bindInteractions() {
  document.querySelectorAll('.btn').forEach(btn=>btn.addEventListener('click',()=>analytics.track('cta_clicked', { label: btn.textContent.trim().replace(/\s+/g,' ') })));
  const toggle=document.querySelector('.menu-toggle'), menu=document.querySelector('.nav-links'); if(toggle && menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.textContent=open?'×':'☰';}); menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>menu.classList.remove('open')));}
  document.querySelectorAll('.pathway-option').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.pathway-option').forEach(x=>x.classList.remove('is-active'));btn.classList.add('is-active'); const maps={'More Customers':'Digital Growth + Analytics + Strategy','Better Visibility':'SEO + Content + Digital Presence','Better Marketing ROI':'Performance Marketing + Analytics','Better Business Decisions':'Analytics + Data Visualization + Strategy','Market Expansion':'Market Research + Strategy + Digital Growth','Better Data':'Business Analytics + Dashboard Design'};document.getElementById('pathway-result').textContent=maps[btn.dataset.pathway];}));
  document.querySelectorAll('.framework-stage').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.framework-stage').forEach(x=>x.classList.remove('is-active'));btn.classList.add('is-active');}));
  drawDiagnostic(); const restart=document.getElementById('restart-diagnostic'); if(restart) restart.addEventListener('click',()=>{diagnosticState.step=0;diagnosticState.answers={};drawDiagnostic();});
  document.querySelectorAll('.dash-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.dash-tab').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');updateDashboard(btn.dataset.dash);})); updateDashboard(); setupCalculator(); setupContactForm();
}

window.addEventListener('hashchange',()=>render(location.hash.slice(1)||'/'));
render(location.hash.slice(1)||'/');
